string  = """Sharad Pawar also hit out at the central and Maharashtra governments over agrarian issues.\n\nHighlights Sharad Pawar had said the public does not doubt PM Modi\'s intentions He
had made the comment regarding controversy surrounding Rafale Deal He asked government to explain why the cost of aircraft was increased\n\nDays after Nationalist Congress Party (NCP) chief Sharad Pawar created a flutter by saying that the public does not doubt Prime Minister Narendra Modi\'s intentions on purchasing Rafale fighter jets from France, the veteran politician today tried to defuse the situation by asserting that he would "never" do something like that.\n\n"Some people have criticised me, saying that I supported him (PM Modi). But I did not support him and will never (do that)," Mr Pawar said at a party meeting in the Marathwada region.\n\nClarifying his stand on the Rafale deal, the
NCP chief said: "They (the government) bought the aircraft. I am saying with all clarity that the government should explain to parliament why the cost of the aircraft rose from Rs 650 crore (per plane) to Rs 1,600 crore."\n\nHe then went on to reiterate his demand for a probe by a
Joint Parliamentary Committee into the Rafale deal, and demanded that the Modi government disclose the price of the 36 fighter jets.\n\nThe immediate reason for Mr Pawar\'s volte-face seems to heightening rebellion inside the party that led to founder-member Tariq Anwar and general secretary Munaf Hakim calling it quits. His statement also stood to endanger the party\'s potential alliance with the Congress in future elections at a time when its president, Rahul Gandhi, has launched a pointed attack on PM Modi.\n\nThe former Defence Minister\'s controversial
statement was well-received by those on the other side of the political spectrum. BJP president Amit Shah even thanked Mr Pawar, tweeting that he had placed "national interests above party politics". "Dear @RahulGandhi, you would be wiser by believing your own ally and a leader of
Pawar Saheb\'s stature," he added.\n\nThe NCP, however, later issued a statement claiming that the media had quoted Mr Pawar "out of context".\n\nMr Pawar also hit out at the central and Maharashtra governments over agrarian issues, and hailed the former United Progressive Alliance government\'s decision to write off farm loans amounting to Rs 71,000 crore.\n\n(With inputs from PTI)"""

print(string.replace('\n',''))


# test sites
# https://www.ndtv.com/india-news/ncp-chief-sharad-pawar-retracts-rafale-remark-amid-stir-would-never-support-prime-minister-narendra-1925222
# https://timesofindia.indiatimes.com/india/nirav-modi-sent-stepbrother-to-hong-kong-to-get-hold-of-diamonds/articleshow/66035825.cms
